### ISSUE TITLE
Next Year Arrow Broken

### ISSUE THREAD

**Issue by joshuayoung1380** [Baremetrics/calendar#48]
I like your plugin. Nice Work.

Just Noticed when you scroll to the previous year using the back arrow for the month.
The arrow to go back forward to 2016 disappears.
  Using Firefox 40.0.3 OS X Yosemite

Does not seem like expected behavior.

Thanks for making your plugin available.

**Comment by kalepail** [comment]
That is actually expected behavior as far as I can tell. The year forward arrow will only exist if that year AND month exist within your range. In the testing I did the month and year did not exist for much of the back tracking.. but eventually the forward arrow did come back when both requirements were met.
